# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_testcontent_content_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcontent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
